version: 0.2

phases:
  build:
    commands:        
      # - yum install pip -y
      # - pip install aws-sam-cli    
      - docker build -t jensonjoseph/node12-hello-world-lambda .
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 967756262698.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t lambda-container .
      - docker tag lambda-container:latest 967756262698.dkr.ecr.us-east-1.amazonaws.com/lambda-container:latest
      - docker push 967756262698.dkr.ecr.us-east-1.amazonaws.com/lambda-container:latest

  post_build:
    commands:
      - aws cloudformation deploy --template-file resources.yml --stack-name lambdacft --capabilities CAPABILITY_NAMED_IAM
      # - |
      #   sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
      #   --s3-bucket $CODEPIPELINE_BUCKET \
      #   --s3-prefix $STACK_NAME \
      #   --region $AWS_REGION \
      #   --stack-name $STACK_NAME \
      #   --capabilities CAPABILITY_IAM \
      #   --parameter-overrides \
      #   Environment=$ENVIRONMENT